import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:crewpoint_app/app/core/env/app_flavor.dart';
import 'package:crewpoint_app/firebase_options_dev.dart' as dev;
import 'package:crewpoint_app/firebase_options_stg.dart' as stg;
import 'package:crewpoint_app/firebase_options_prod.dart' as prod;

/// Initializes Firebase using options generated by `flutterfire configure`.
abstract final class FirebaseService {
  /// Firestore instance settings applied once at startup, before any
  /// Firestore call.
  ///
  /// `persistenceEnabled: true` is the Pillar 1 contract on every platform:
  ///
  /// - **iOS / Android** — already the `cloud_firestore` default. Declared
  ///   here so the guarantee is explicit rather than inherited, and so a
  ///   future SDK default-flip can't silently disable it.
  /// - **Web** — NOT the default, and the reason this constant exists (V1
  ///   launch blocker #6). The web plugin maps `persistenceEnabled: true`
  ///   onto the modern JS `persistentLocalCache(...)` — not the deprecated
  ///   `enableIndexedDbPersistence()` — so reads hydrate from IndexedDB on
  ///   cold start and queued writes survive a reload.
  ///
  /// `cacheSizeBytes` is intentionally left unset: the SDK default (40 MB,
  /// LRU-evicted) applies. Do NOT reach for [Settings.CACHE_SIZE_UNLIMITED]
  /// here — on web that removes the ceiling on IndexedDB growth.
  ///
  /// Web multi-tab caveat: the plugin's `Settings` API exposes no tab
  /// manager, so persistence is single-tab. The first tab takes the lease;
  /// additional tabs run against an in-memory cache and log a console
  /// warning. They stay fully functional online — nothing throws, and no
  /// call site needs to handle it.
  static const Settings firestoreSettings = Settings(persistenceEnabled: true);

  static Future<void> initialize({AppFlavor flavor = AppFlavor.dev}) async {
    final options = switch (flavor) {
      AppFlavor.dev => dev.DefaultFirebaseOptions.currentPlatform,
      AppFlavor.stg => stg.DefaultFirebaseOptions.currentPlatform,
      AppFlavor.prod => prod.DefaultFirebaseOptions.currentPlatform,
    };

    await Firebase.initializeApp(options: options);

    // Must land before the first Firestore read/write — the SDK freezes its
    // settings once the instance is used. `main()` calls this ahead of
    // `runApp`, so no provider has touched Firestore yet.
    FirebaseFirestore.instance.settings = firestoreSettings;
  }
}
