import 'package:firebase_core/firebase_core.dart';
import 'package:crewpoint_app/app/core/env/app_flavor.dart';
import 'package:crewpoint_app/firebase_options_dev.dart' as dev;
import 'package:crewpoint_app/firebase_options_stg.dart' as stg;
import 'package:crewpoint_app/firebase_options_prod.dart' as prod;

/// Initializes Firebase using options generated by `flutterfire configure`.
abstract final class FirebaseService {
  static Future<void> initialize({AppFlavor flavor = AppFlavor.dev}) async {
    final options = switch (flavor) {
      AppFlavor.dev => dev.DefaultFirebaseOptions.currentPlatform,
      AppFlavor.stg => stg.DefaultFirebaseOptions.currentPlatform,
      AppFlavor.prod => prod.DefaultFirebaseOptions.currentPlatform,
    };

    await Firebase.initializeApp(options: options);
  }
}
