import 'package:firebase_core/firebase_core.dart';
import 'package:crewpoint_app/app/core/env/app_flavor.dart';

/// Initializes Firebase using options generated by `flutterfire configure`.
///
/// Generated files expected at:
/// - `lib/firebase_options_dev.dart`
/// - `lib/firebase_options_stg.dart`
/// - `lib/firebase_options_prod.dart`
///
/// Until those files are generated, uses placeholder options.
abstract final class FirebaseService {
  static Future<void> initialize({AppFlavor flavor = AppFlavor.dev}) async {
    // TODO: Replace with generated options once `flutterfire configure` is run:
    //
    // import 'package:crewpoint_app/firebase_options_dev.dart' as dev;
    // import 'package:crewpoint_app/firebase_options_stg.dart' as stg;
    // import 'package:crewpoint_app/firebase_options_prod.dart' as prod;
    //
    // final options = switch (flavor) {
    //   AppFlavor.dev => dev.DefaultFirebaseOptions.currentPlatform,
    //   AppFlavor.stg => stg.DefaultFirebaseOptions.currentPlatform,
    //   AppFlavor.prod => prod.DefaultFirebaseOptions.currentPlatform,
    // };
    //
    // await Firebase.initializeApp(options: options);

    // Placeholder until flutterfire configure is run:
    await Firebase.initializeApp(
      options: const FirebaseOptions(
        apiKey: 'PLACEHOLDER',
        appId: 'PLACEHOLDER',
        messagingSenderId: 'PLACEHOLDER',
        projectId: 'PLACEHOLDER',
      ),
    );
  }
}
