// Environment configuration for non-Firebase secrets.
//
// Firebase keys are auto-generated by `flutterfire configure`
// into `lib/firebase_options_{flavor}.dart` — they are NOT stored here.
//
// To add non-Firebase secrets:
// 1. Add keys to `.env`
// 2. Uncomment the envied code below and add fields
// 3. Run `dart run build_runner build -d`
//
// import 'package:envied/envied.dart';
//
// part 'env.g.dart';
//
// @Envied(path: '.env')
// abstract class Env {
//   @EnviedField(varName: 'SOME_API_KEY', obfuscate: true)
//   static final String someApiKey = _Env.someApiKey;
// }

/// Placeholder class — will be replaced by envied-generated code
/// once non-Firebase secrets are added to `.env`.
abstract final class Env {
  // No Firebase keys here — they come from firebase_options_{flavor}.dart
}
