import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:crewpoint_app/app/core/constants/app_pdf_theme.dart';
import 'package:crewpoint_app/app/features/budget/data/member_name_resolver.dart';
import 'package:crewpoint_app/app/features/dashboard/domain/models/event.dart';
import 'package:crewpoint_app/app/features/tasks/domain/models/task.dart';

/// Buckets tasks by [TaskStatus] preserving the input order within each
/// bucket. Pure helper exposed for unit testing the grouping policy
/// independently of the PDF render.
Map<TaskStatus, List<TaskModel>> groupTasksByStatus(List<TaskModel> tasks) {
  return {
    for (final s in TaskStatus.values)
      s: tasks.where((t) => t.status == s).toList(growable: false),
  };
}

/// Returns a "done/total" label for a task's checklist, or null when the
/// task has no checklist items at all.
String? checklistProgressLabel(TaskModel task) {
  if (task.checklistItems.isEmpty) return null;
  final done = task.checklistItems.where((i) => i.isCompleted).length;
  return '$done/${task.checklistItems.length}';
}

/// Builds a branded task report PDF for an event.
///
/// Sections by status (Done / In Progress / To Do) with row counts;
/// each row shows title, assignee, due date, completed-by/at when Done,
/// and checklist progress fraction when present.
Future<Uint8List> buildTaskReport({
  required EventModel event,
  required List<TaskModel> tasks,
  required Map<String, String> memberNames,
}) async {
  final grouped = groupTasksByStatus(tasks);
  final doc = pw.Document();

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.letter,
      margin: const pw.EdgeInsets.all(32),
      build: (context) => [
        _header(event),
        pw.SizedBox(height: 16),
        for (final status in [
          TaskStatus.done,
          TaskStatus.inProgress,
          TaskStatus.todo,
        ]) ...[
          _statusSection(status, grouped[status] ?? const [], memberNames),
          pw.SizedBox(height: 12),
        ],
      ],
      footer: (context) => pw.Container(
        alignment: pw.Alignment.centerRight,
        margin: const pw.EdgeInsets.only(top: 12),
        child: pw.Text(
          'Page ${context.pageNumber} of ${context.pagesCount}  ·  Generated by CrewPoint',
          style: const pw.TextStyle(
            color: AppPdfTheme.charcoalLight,
            fontSize: 9,
          ),
        ),
      ),
    ),
  );

  return doc.save();
}

pw.Widget _header(EventModel event) {
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(
        event.title,
        style: pw.TextStyle(
          fontSize: 24,
          fontWeight: pw.FontWeight.bold,
          color: AppPdfTheme.charcoal,
        ),
      ),
      pw.SizedBox(height: 4),
      pw.Text(
        'Tasks  ·  Generated ${DateTime.now().toIso8601String()}',
        style: const pw.TextStyle(
          color: AppPdfTheme.charcoalLight,
          fontSize: 10,
        ),
      ),
    ],
  );
}

pw.Widget _statusSection(
  TaskStatus status,
  List<TaskModel> tasks,
  Map<String, String> memberNames,
) {
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(
        '${status.label} (${tasks.length})',
        style: pw.TextStyle(
          fontSize: 14,
          fontWeight: pw.FontWeight.bold,
          color: AppPdfTheme.sage,
        ),
      ),
      pw.SizedBox(height: 4),
      if (tasks.isEmpty)
        pw.Text(
          'No ${status.label.toLowerCase()} tasks',
          style: pw.TextStyle(
            color: AppPdfTheme.charcoalLight,
            fontStyle: pw.FontStyle.italic,
          ),
        )
      else
        for (final t in tasks) _taskRow(t, memberNames),
    ],
  );
}

pw.Widget _taskRow(TaskModel task, Map<String, String> memberNames) {
  final assignee = task.assigneeId == null
      ? null
      : resolveMemberName(uid: task.assigneeId, memberNames: memberNames);
  final dueLabel = task.dueDate?.toIso8601String().split('T').first;
  final progress = checklistProgressLabel(task);

  final completedLabel = task.status == TaskStatus.done
      ? [
          if (task.completedBy != null)
            'by ${resolveMemberName(uid: task.completedBy, memberNames: memberNames)}',
          if (task.completedAt != null)
            'at ${task.completedAt!.toIso8601String().split('T').first}',
        ].where((s) => s.isNotEmpty).join(' ')
      : null;

  return pw.Padding(
    padding: const pw.EdgeInsets.symmetric(vertical: 4),
    child: pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          task.title,
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
        ),
        pw.Text(
          [
            if (assignee != null) 'Assignee: $assignee',
            if (dueLabel != null) 'Due: $dueLabel',
            if (progress != null) 'Checklist: $progress',
            if (completedLabel != null && completedLabel.isNotEmpty)
              'Completed $completedLabel',
          ].join('  ·  '),
          style: const pw.TextStyle(
            color: AppPdfTheme.charcoalLight,
            fontSize: 10,
          ),
        ),
      ],
    ),
  );
}
