import 'dart:developer' as developer;
import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:crewpoint_app/app/core/constants/app_pdf_theme.dart';
import 'package:crewpoint_app/app/features/budget/domain/models/balance_ledger.dart';
import 'package:crewpoint_app/app/features/budget/domain/models/expense.dart';
import 'package:crewpoint_app/app/features/dashboard/domain/models/event.dart';

/// Optional receipt loader. Returns the receipt bytes for a given
/// `receiptPath` or `null` if the receipt is not available. Allowed to
/// throw — the builder catches and falls back to a placeholder so the
/// report never fails to generate because a single thumbnail couldn't
/// load.
typedef ReceiptLoader = Future<Uint8List?> Function(String path);

/// Hard cap on rendered expense rows. Keeps the in-browser dart2js
/// builder bounded; rows beyond the cap are summarized with a "Truncated"
/// trailing line.
const int kMaxRenderedExpenses = 200;

/// Decides which expense rows render and whether a "Truncated" footer
/// applies. Pure function — exposed for unit testing the cap policy
/// independently of the PDF render.
({List<ExpenseModel> rendered, bool truncated}) truncateExpensesForRender(
  List<ExpenseModel> expenses, {
  int maxRendered = kMaxRenderedExpenses,
}) {
  if (expenses.length <= maxRendered) {
    return (rendered: expenses, truncated: false);
  }
  return (rendered: expenses.take(maxRendered).toList(), truncated: true);
}

/// Builds a branded expense report PDF for an event.
///
/// Pure Dart: only the `pdf` package is imported. No Flutter / Firebase
/// dependencies, so it runs in unit tests without a binding.
Future<Uint8List> buildExpenseReport({
  required EventModel event,
  required List<ExpenseModel> expenses,
  required Map<String, String> memberNames,
  required BalanceLedger ledger,
  ReceiptLoader? receiptLoader,
}) async {
  final cap = truncateExpensesForRender(expenses);
  final renderable = cap.rendered;
  final truncated = cap.truncated;

  // Pre-resolve receipt thumbnails so the PDF render path stays sync.
  final thumbnails = <String, Uint8List?>{};
  if (receiptLoader != null) {
    for (final e in renderable) {
      final path = e.receiptPath;
      if (path == null || path.isEmpty) continue;
      try {
        thumbnails[path] = await receiptLoader(path);
      } catch (err, st) {
        developer.log(
          'Failed to load receipt for expense ${e.id}; using placeholder',
          name: 'expense_pdf_builder',
          error: err,
          stackTrace: st,
        );
        thumbnails[path] = null;
      }
    }
  }

  final doc = pw.Document();

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.letter,
      margin: const pw.EdgeInsets.all(32),
      build: (context) => [
        _header(event),
        pw.SizedBox(height: 16),
        _balancesBlock(ledger, memberNames, event.currency),
        pw.SizedBox(height: 16),
        _settlementsBlock(ledger.settlements, memberNames, event.currency),
        pw.SizedBox(height: 16),
        if (renderable.isEmpty)
          pw.Text(
            'No expenses yet',
            style: pw.TextStyle(
              color: AppPdfTheme.charcoalLight,
              fontStyle: pw.FontStyle.italic,
            ),
          )
        else
          ..._expensesTable(
            renderable,
            memberNames,
            thumbnails,
            event.currency,
          ),
        if (truncated) ...[
          pw.SizedBox(height: 12),
          pw.Text(
            'Truncated — filter to see more (${expenses.length - kMaxRenderedExpenses} additional rows omitted)',
            style: const pw.TextStyle(color: AppPdfTheme.terracotta),
          ),
        ],
      ],
      footer: (context) => pw.Container(
        alignment: pw.Alignment.centerRight,
        margin: const pw.EdgeInsets.only(top: 12),
        child: pw.Text(
          'Page ${context.pageNumber} of ${context.pagesCount}  ·  Generated by CrewPoint',
          style: const pw.TextStyle(
            color: AppPdfTheme.charcoalLight,
            fontSize: 9,
          ),
        ),
      ),
    ),
  );

  return doc.save();
}

pw.Widget _header(EventModel event) {
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(
        event.title,
        style: pw.TextStyle(
          fontSize: 24,
          fontWeight: pw.FontWeight.bold,
          color: AppPdfTheme.charcoal,
        ),
      ),
      pw.SizedBox(height: 4),
      pw.Text(
        'Currency: ${event.currency}  ·  '
        'Generated ${DateTime.now().toIso8601String()}',
        style: const pw.TextStyle(
          color: AppPdfTheme.charcoalLight,
          fontSize: 10,
        ),
      ),
    ],
  );
}

pw.Widget _balancesBlock(
  BalanceLedger ledger,
  Map<String, String> memberNames,
  String currency,
) {
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(
        'Total spent: ${ledger.totalExpenses.toStringAsFixed(2)} $currency',
        style: pw.TextStyle(
          fontSize: 14,
          fontWeight: pw.FontWeight.bold,
          color: AppPdfTheme.sage,
        ),
      ),
      pw.SizedBox(height: 8),
      pw.Text(
        'Member balances',
        style: pw.TextStyle(
          fontSize: 12,
          fontWeight: pw.FontWeight.bold,
          color: AppPdfTheme.charcoal,
        ),
      ),
      pw.SizedBox(height: 4),
      for (final entry in ledger.netBalances.entries)
        pw.Text(
          '${memberNames[entry.key] ?? entry.key}: '
          '${entry.value.toStringAsFixed(2)} $currency',
          style: pw.TextStyle(
            color: entry.value < 0 ? AppPdfTheme.terracotta : AppPdfTheme.sage,
          ),
        ),
    ],
  );
}

pw.Widget _settlementsBlock(
  List<Settlement> settlements,
  Map<String, String> memberNames,
  String currency,
) {
  if (settlements.isEmpty) return pw.SizedBox();
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(
        'Settle up',
        style: pw.TextStyle(
          fontSize: 12,
          fontWeight: pw.FontWeight.bold,
          color: AppPdfTheme.charcoal,
        ),
      ),
      pw.SizedBox(height: 4),
      for (final s in settlements)
        pw.Text(
          '${memberNames[s.fromUserId] ?? s.fromUserId} -> '
          '${memberNames[s.toUserId] ?? s.toUserId}: '
          '${s.amount.toStringAsFixed(2)} $currency',
        ),
    ],
  );
}

List<pw.Widget> _expensesTable(
  List<ExpenseModel> expenses,
  Map<String, String> memberNames,
  Map<String, Uint8List?> thumbnails,
  String currency,
) {
  return [
    pw.Text(
      'Expenses',
      style: pw.TextStyle(
        fontSize: 12,
        fontWeight: pw.FontWeight.bold,
        color: AppPdfTheme.charcoal,
      ),
    ),
    pw.SizedBox(height: 4),
    for (final e in expenses) _expenseRow(e, memberNames, thumbnails, currency),
  ];
}

pw.Widget _expenseRow(
  ExpenseModel e,
  Map<String, String> memberNames,
  Map<String, Uint8List?> thumbnails,
  String currency,
) {
  final receiptPath = e.receiptPath;
  final thumb = receiptPath == null ? null : thumbnails[receiptPath];
  return pw.Padding(
    padding: const pw.EdgeInsets.symmetric(vertical: 4),
    child: pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        _receiptThumb(thumb, hasReceipt: receiptPath != null),
        pw.SizedBox(width: 8),
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                e.description ?? '(no description)',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.Text(
                '${memberNames[e.payerId] ?? '(no longer in event)'}  ·  '
                '${e.amount.toStringAsFixed(2)} $currency',
                style: const pw.TextStyle(
                  color: AppPdfTheme.charcoalLight,
                  fontSize: 10,
                ),
              ),
            ],
          ),
        ),
      ],
    ),
  );
}

pw.Widget _receiptThumb(Uint8List? bytes, {required bool hasReceipt}) {
  if (bytes != null) {
    try {
      return pw.SizedBox(
        width: 40,
        height: 40,
        child: pw.Image(pw.MemoryImage(bytes), fit: pw.BoxFit.cover),
      );
    } catch (err, st) {
      developer.log(
        'pdf failed to embed receipt image; using placeholder',
        name: 'expense_pdf_builder',
        error: err,
        stackTrace: st,
      );
      // fall through to placeholder
    }
  }

  // Slate-grey placeholder for missing / failed receipts and for
  // expenses that have no receipt at all.
  return pw.Container(
    width: 40,
    height: 40,
    decoration: const pw.BoxDecoration(color: AppPdfTheme.slate),
    alignment: pw.Alignment.center,
    child: pw.Text(
      hasReceipt ? 'no\nimage' : '—',
      textAlign: pw.TextAlign.center,
      style: const pw.TextStyle(color: AppPdfTheme.white, fontSize: 6),
    ),
  );
}
