// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDixC7AUjyQLBvBTddRwIBi1y7XU79LSJw',
    appId: '1:394956084700:web:9a26cd6a360e6cec52ab19',
    messagingSenderId: '394956084700',
    projectId: 'crewpoint-prod',
    authDomain: 'crewpoint-prod.firebaseapp.com',
    storageBucket: 'crewpoint-prod.firebasestorage.app',
    measurementId: 'G-2RJCSXKHYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8WvWFzrBQCiMp7ZwVQ8c-qUpDceBnSxU',
    appId: '1:394956084700:android:04992e46e35351bf52ab19',
    messagingSenderId: '394956084700',
    projectId: 'crewpoint-prod',
    storageBucket: 'crewpoint-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXdTk75t4T8Vp8kCn115oCwe432an-LpU',
    appId: '1:394956084700:ios:4803c60efff8d6b852ab19',
    messagingSenderId: '394956084700',
    projectId: 'crewpoint-prod',
    storageBucket: 'crewpoint-prod.firebasestorage.app',
    androidClientId: '394956084700-d6u1iultapr5r785a4l72mnojonht8m5.apps.googleusercontent.com',
    iosClientId: '394956084700-vk8cbpb88f6cicdlrn3mh1tcr0od698v.apps.googleusercontent.com',
    iosBundleId: 'space.sookoon.crewpoint.app',
  );

}