// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgvlcN_IZRe8XXAtFS_qVGrSBkIwPiZVo',
    appId: '1:711822236757:web:7fc7f232d8f717188788dc',
    messagingSenderId: '711822236757',
    projectId: 'crewpoint-dev',
    authDomain: 'crewpoint-dev.firebaseapp.com',
    storageBucket: 'crewpoint-dev.firebasestorage.app',
    measurementId: 'G-G8SRKQ7RZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPLYkjk6WjW0_CGT6ehsHWbj7dZyvgeuM',
    appId: '1:711822236757:android:eed756cdb3cb14d48788dc',
    messagingSenderId: '711822236757',
    projectId: 'crewpoint-dev',
    storageBucket: 'crewpoint-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD37ic_Hta7x533jaRln-WuD2IHh38Lo_Y',
    appId: '1:711822236757:ios:c10e4a2c1788a40d8788dc',
    messagingSenderId: '711822236757',
    projectId: 'crewpoint-dev',
    storageBucket: 'crewpoint-dev.firebasestorage.app',
    iosClientId: '711822236757-aes0f8510iha8vatncbc2031ctb607pg.apps.googleusercontent.com',
    iosBundleId: 'space.sookoon.crewpointApp',
  );
}
