// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjDMnW_prMhOtj6mytmcaUFOsinE4Rng',
    appId: '1:715030987637:web:588e1db0f6255fc77a093c',
    messagingSenderId: '715030987637',
    projectId: 'crewpoint-stg',
    authDomain: 'crewpoint-stg.firebaseapp.com',
    storageBucket: 'crewpoint-stg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMnekahKvInwwM__eYlR3QKXEMvaymwbM',
    appId: '1:715030987637:android:7bd1a6bc200f2c337a093c',
    messagingSenderId: '715030987637',
    projectId: 'crewpoint-stg',
    storageBucket: 'crewpoint-stg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIwv_UGTBtI9cP1Ri569yO71RpAMu_7FI',
    appId: '1:715030987637:ios:a4daa6543962aa0e7a093c',
    messagingSenderId: '715030987637',
    projectId: 'crewpoint-stg',
    storageBucket: 'crewpoint-stg.firebasestorage.app',
    androidClientId: '715030987637-m6bj843oqjh18v2foj20s3kkn0fhmh67.apps.googleusercontent.com',
    iosClientId: '715030987637-0mkbfpdkpn3thoficscmdmapstgi36mu.apps.googleusercontent.com',
    iosBundleId: 'space.sookoon.crewpoint.stg',
  );

}